name: SOS Emulator Build

on: 
  push:
    branches: 
      - main

jobs:
  build-emulator:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    - name: install app dependencies and build it
      run: yarn && yarn build
    - name: build with verbose
      run: yarn tauri build --verbose
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v2
      if: matrix.platform == 'ubuntu-latest'
      with:
        name: linux-appimage-sos-emulator
        path: src-tauri/target/release/bundle/appimage/*
    - uses: actions/upload-artifact@v2
      if: matrix.platform == 'ubuntu-latest'
      with:
        name: linux-deb-sos-emulator
        path: src-tauri/target/release/bundle/deb/*
    - uses: actions/upload-artifact@v2
      if: matrix.platform == 'windows-latest'
      with:
        name: windows-sos-emulator
        path: src-tauri/target/release/bundle/msi/*
    - uses: actions/upload-artifact@v2
      if: matrix.platform == 'macos-latest'
      with:
        name: macos-sos-emulator
        path: src-tauri/target/release/bundle/dmg/*